version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: my-node_app
    ports:
      - "3000:3000"
    environment:
      - PG_DB=producao_rascunho_db
      - PG_USER=db_user
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db
    volumes:
      - ./uploads:/app/uploads
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=producao_rascunho_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}


