version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: my-node_app
    ports:
      - "3000:3000"
    env_file:
      - .env 
    restart: always
    depends_on:
      - node_db
    volumes:
      - ./uploads:/app/uploads
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env  
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}


