### Localhost

###
GET http://localhost:3000/

### Usuários
###
GET http://localhost:3000/users

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Empresa 3",
    "email": "empresa1@email.com",
    "cnpj": "99.187.675/0601-43", 
    "tipo": "Comum",
    "status": "Pendente",
    "rgp": "AA12696698",
    "cep": "72000000",
    "uf": "DF"

}

###
GET http://localhost:3000/users/20


###
DELETE http://localhost:3000/users/16


### Embarcações
###
GET http://localhost:3000/embarcacoes

### 
POST http://localhost:3000/embarcacoes
Content-Type: application/json

{
    "name": "Barquinho",
    "rgp": "MA123467950",
    "uf": "CE"

}

### Espécies
###
GET http://localhost:3000/especies


### 
POST http://localhost:3000/especies
Content-Type: application/json

{
    "nomeComum": "Albacora bandolim",
    "nomeCientifico": "Thunnus obesus"

}

### 
POST http://localhost:3000/especies
Content-Type: application/json

{
    "nomeComum": "Bonito listrado",
    "nomeCientifico": "Katsuwonus pelamis "

}


### Mapas de Produção
###
GET http://localhost:3000/producoes


### 
POST http://localhost:3000/producoes
Content-Type: application/json

{
  "dataInicial": "2024-06-05",
  "dataFinal": "2024-05-05",
  "userId": "1"
}

### 
POST http://localhost:3000/producoes
Content-Type: application/json

{
  "dataInicial": "2024-06-04",
  "dataFinal": "2024-05-09",
  "userId": "2"
}


### UserEmbarcacao
###
GET http://localhost:3000/userEmbarcacoes

### 
POST http://localhost:3000/userEmbarcacoes
Content-Type: application/json

{
  "userId": 1,
  "embarcacaoId": 1
}

### ProducaoEmbarcacaoEspecie
###
GET http://localhost:3000/producaoEmbarcacaoEspecies

### 
POST http://localhost:3000/producaoEmbarcacaoEspecies
Content-Type: application/json

{
  "producaoId": 3,
  "embarcacaoId": 2,
  "especieId": 2,
  "peso": 6.5
}

### 
POST http://localhost:3000/producaoEmbarcacaoEspecies
Content-Type: application/json

{
  "producaoId": 7,
  "embarcacaoId": 2,
  "especieId": 1,
  "peso": 6.5
}

###
GET http://localhost:3000/consultas/1