### Localhost

###
GET http://localhost:3000/

### Usuários
###
GET http://localhost:3000/users

### 
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Empresa 3",
    "email": "empresa1@email.com",
    "cnpj": "97.177.975/0601-43", 
    "tipo": "Comum",
    "status": "Pendente",
    "rgp": "AA12346978",
    "cep": "72000000",
    "uf": "DF"

}

###
GET http://localhost:3000/users/20


###
DELETE http://localhost:3000/users/16


### Embarcações
###
GET http://localhost:3000/embarcacoes

### 
POST http://localhost:3000/embarcacoes
Content-Type: application/json

{
    "name": "Barquinho II",
    "rgp": "MA123469558",
    "uf": "MA"

}

### Espécies
###
GET http://localhost:3000/especies


### 
POST http://localhost:3000/especies
Content-Type: application/json

{
    "nomeComum": "Albacora bandolim",
    "nomeCientifico": "Thunnus obesus"

}

### 
POST http://localhost:3000/especies
Content-Type: application/json

{
    "nomeComum": "Bonito listrado",
    "nomeCientifico": "Katsuwonus pelamis "

}


### Mapas de Produção
###
GET http://localhost:3000/producoes


### 
POST http://localhost:3000/producoes
Content-Type: application/json

{
  "dataInicial": "2024-06-05",
  "dataFinal": "2025-05-05",
  "userId": "20"
}

### 
POST http://localhost:3000/producoes
Content-Type: application/json

{
  "dataInicial": "2024-06-04",
  "dataFinal": "2024-05-09",
  "userId": "99"
}